import { ReactNode } from "react";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CFT Problem lists",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "black",
  initialScale: 1.0,
  width: "device-width",
};

export default function MainLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en" className={"dark"}>
      <body
        className={twMerge(inter.className, "flex flex-col overflow-y-visible")}
      >
        <div id={"modal"}>{modal}</div>
        <div id={"root"}>{children}</div>
      </body>
    </html>
  );
}
