import { ReactNode } from "react";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import PageHeading from "@/components/Navbar/PageHeading";
import { checkUser } from "@/actions/auth-actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CFT Problem lists",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "black",
  initialScale: 1.0,
  width: "device-width",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  await checkUser();

  return (
    <>
      <PageHeading />
      <main className={"flex flex-col mt-24 h-[90%] overflow-y-visible"}>
        {children}
      </main>
    </>
  );
}
